import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@pp/styles/Home.module.css";
import { useEffect } from "react";
import useSWR, { Fetcher } from "swr";
import { Appointment } from "@pp/utils";
import { useRouter } from "next/router";
import { List } from "@pp/components";

const inter = Inter({ subsets: ["latin"] });

const fetcher: Fetcher<{ appointments: Appointment[] }, string> = (url) =>
  fetch(url, {
    method: "GET",
  }).then((r) => r.json());

export default function Appointments() {
  const router = useRouter();
  const { uuid } = router.query;
  const { data, error, isLoading } = useSWR(
    `/api/users/${uuid}/appointments`,
    fetcher
  );

  const showList = data?.appointments && !isLoading && !error

  return (
    <>
      <Head>
        <title>Boost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showList && <List appointments={data?.appointments} />}
      </main>
    </>
  );
}
